# Generated by Django 5.2.9 on 2026-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montagem', '0002_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(default='/', max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Acesso ao site',
                'verbose_name_plural': 'Acessos ao site',
                'ordering': ['-criado_em'],
            },
        ),
    ]
